### PR TITLE
Fix H1 font size problem

### PR DESCRIPTION
**Pull request by hnc-jihoon**
- by applying https://github.com/jekyll/minima/pull/273,
  before an official update of minima theme.

(before)
image
-> (after)
image

### CODE REVIEW

**Review by hnc-kypark — APPROVED** [review]
Looks good to me. Thanks. 👍

**Review by hnc-pjs — APPROVED** [review]
As I reported, ".post-content h1" was missing. Now it looks like that ".post-content h1" is extended from ".post-title h1".
In my opinion, "h1" should be added in ".post-content" in "minima's layout.scss" with the other hX series. But it's OK for now.

**Comment by hnc-jihoon** [comment]
My intention is to apply the same style on ".post-content h1" with ".post-title", as the original PR(https://github.com/jekyll/minima/pull/273) did.
Because the stable version of minima theme is not updated yet with that fix, this kind of temporal patch is needed, I think.

**Comment by hnc-pjs** [comment]
So, when the minima theme stable version is updated, this modification would be reverted?

**Comment by hnc-jihoon** [comment]
Yes, at that time this modification would not be needed anymore. (Thus I added a TODO comment)

**Pull request merged**
