### PR TITLE
Change title image

### LINKED ISSUE #17: 한컴 블로그 해더의 타이틀 고찰
"&lt;/Tech&gt; 블로그"

- &lt;/Tech&gt;는 "Tech" 라는 태그를 닫는다는 의미로
  블로그가 끝났다거나, 앞쪽의 여는 태그 이후에 에러가 발생해서 닫는 태그가 텍스트로 노출된 것으로 생각할 수 있습니다.
- 열리고 닫는 것을 모두 나타내는 empty tag를 사용하면 좋을 것 같네요.
- HTML5는 태그 이름의 대소문자를 구분하지 않지만 모두 소문자로 하기를 권고하고 있으므로
  1) 심미적 문학적 관점에서 대문자로 시작하는 것도 나쁘지 않겠고
  2) 모두 소문자로 표기하면 좀 더 기술적이라고 하겠음

이에 아래 2가지 안을 제안 합니다.
1) "&lt;Tech /&gt; 블로그"
2) "&lt;tech /&gt; 블로그"

의견 부탁드립니다.

### PR DESCRIPTION
**Pull request by hnc-jihoon**
- `</Tech>` -> `<Tech/>`
- fix #17

### CODE REVIEW

**Review by hnc-pjs — COMMENTED** [review]
I checked that the image of title had changed to "<Tech/>". There is no space between "Tech" and "/", so I want to ask whether it is the designer's decision or just a mistake.
If it is the designer's decision, then it'll be OK. But if it is a mistake, then it should be corrected.

**Comment by hnc-jihoon** [comment]
As we checked, it was the designer's intention. :)

**Comment by hnc-pjs** [comment]
I agree with the designer's choice!

**Comment by hnc-jihoon** [comment]
then, would anybody approve this PR, please?

**Review by hnc-jglee — APPROVED** [review]
LGTM

**Pull request merged**
